### PR TITLE
Python source code formatting

### PR DESCRIPTION
**Pull request by AxylumRust**

### CODE REVIEW

**Comment by HalilDeniz** [comment]
Thank you for your update.

**Comment by AxylumRust** [comment]
You are welcome.

**Comment by HalilDeniz** [comment]
Can you help with something?

**Comment by AxylumRust** [comment]
How can I help you?

**Comment by HalilDeniz** [comment]
im improving a code name of CryptoChat
https://github.com/HalilDeniz/CryptoChat
When I send a large message, the messages are sent in pieces. 
The message must reach the other party in one piece.
Can you make an edit to fix this and send it to me along with the pull request?
https://github.com/HalilDeniz/CryptoChat/discussions/5

**Comment by AxylumRust** [comment]
I will take a look at the code, but I cannot guarantee that I will be able to do it ;-)

**Pull request merged**
